name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.21
  - scipy=1.6
  - matplotlib=3.5
  - astropy=4.2
  - gwpy=2.0
  - h5py=3.1
  - ipykernel=5.5
  - decorator=5.1

